### ISSUE TITLE
Trello board just like the one in Computer Science

### ISSUE THREAD

**Issue by saip009** [ossu/data-science#27]
Did anyone make a trello board for themselves and can share it?  Or can someone make it? 
I'm also making it, slowly though. Will share when I finish it.

**Comment by ShogoMiyagi** [comment]
Hi, I made it.
Please check it your self.
It's all yours.
https://trello.com/b/WpdTlfdW/ossu-data-science-public

**Comment by beginrescueend** [comment]
Thanks for that.  I also created a similar Trello board to those two, but for Machine Learning in Keras: https://trello.com/b/P4DDJjLE/

**Comment by brylie** [comment]
@beginrescueend I appreciate that your board provides a beginner friendly approach that is not *frontloaded* with years of mathematics. I really believe that Machine Learning/Deep Learning, etc. can be useful to people without years of acedemic knowledge, if we can just present the materials in simple format and sequence. E.g. **starting from how to use it** rather than the theoretical foundations.

**Comment by beginrescueend** [comment]
Thanks!  I originally wrote it for myself, since I found the same difficulty.
