### ISSUE TITLE
Login whit github

### ISSUE THREAD

**Issue by qselmer** [ossu/data-science#50]
{
        "error": {
                "code":"SERVICE_UNAVAILABLE",
                "statusCode":410,
                "message":"SDK Update Required: See https://goo.gl/2cKQWm.",
                "details":"SDK Update Required: See https://goo.gl/2cKQWm."
        }
}

**Comment by abdulwahidgul24085** [comment]
![image](https://user-images.githubusercontent.com/6042059/66713437-05e46700-edbc-11e9-8e7b-d77d635307bd.png)

I am having the following error when trying to login with github

**Comment by somaditya** [comment]
I was facing the same issue.

**Comment by abdulwahidgul24085** [comment]
I have made a pull request to fix the problem, but I am not able to get the project started with the configuration instructions provided. I am not sure if the project is live any more. Since the last commit was like a year ago

**Comment by jogonzro** [comment]
Is this full course worth it over other full courses from datacamp or similar? This is pretty huge and it seems to not focus very much at the start.

It's a big progect and I don't want to waste the precious time, since it's a year... And not being able to sing in in the app is not a good signal.

**Comment by abdulwahidgul24085** [comment]
I want to checkout the website that the guy has build. I saw an eassy fixable error. I though I could help. I am not a javascript expert. But the problem is that I can't run the project on my local machine based on the instruction provided. 

But coming to your first question. I don't want to influence your answer. I have attached the following to graphs which tells you the course and the effort in hours and percentage that you need to follow along.

![efforts_hours](https://user-images.githubusercontent.com/6042059/67159711-8d504e00-f359-11e9-85b7-734edd558b8f.PNG)

![effor_percentage](https://user-images.githubusercontent.com/6042059/67159714-93462f00-f359-11e9-8ee6-0e4ae2c3d1f4.PNG)

How I calculated hours? I multiple the number of hours into the number of week to complete the course. This gave me approximated idea of how much effort I need to put in to what course. So, if you know some courses like programming with python you don't need to do that, or put to much effort. I hope this helps you in answering your question. For me I am going heavy on the probability and Statistics. Since a lot of good open source library takes care of the math. So to get started I don't need to brought down by the math. Once I know what the models are and what are they used for. I will jump into the math. This is my approach.  Happy learning.

**Comment by jogonzro** [comment]
Thanks a lot. That's very informative. I think im gonna mix this course with datacamp courses since those are more easy to follow and find. Thank you a lot.

**Comment by MuskanPaliwal** [comment]
Hi everyone. Login with github option on the webapp always says "This site can't be reached". Can someone help me with this?
