### ISSUE TITLE
Is this course still relevant?

### ISSUE THREAD

**Issue by twisp007** [ossu/data-science#54]
Last update on this course is made 3 years ago so is it still relevant? Like are there better free courses out there than the ones listed here? I am planning on starting this. Anything I need to know?

**Comment by serdtseva** [comment]
@twisp007 

Some courses have been outdated and some of them aren't available anymore, so it's impossible go through the curriculum course-by-course.

**Comment by Nicoivazquez** [comment]
Is there a place where it is being kept up to date?

**Comment by Jarmos-san** [comment]
It's unfortunate but it appears the project is abandoned by the official maintainers. Else it would have been possible to actually crawl through dead links or alike & fix them. 

Besides, just my opinion, I doubt if it's at all possible to follow through every single course & master Data Science. 

So for people looking forward to making a career in Data Science, I usually just refer the following discussions to them.

1. [[D] A Super Harsh Guide to Machine Learning - r/MachineLearning](https://www.reddit.com/r/MachineLearning/comments/5z8110/d_a_super_harsh_guide_to_machine_learning/) & here's a [comment](https://www.reddit.com/r/MachineLearning/comments/5z8110/d_a_super_harsh_guide_to_machine_learning/dewb8ty?utm_source=share&utm_medium=web2x) from the discussion;

> Still not enough. Come up with a novel problem where there’s no training data and figure out how to collect some. Learn to write a scraper, then do some labeling and feature extraction. Install everything on EC2 and automate it. Write code to continuously retrain and redeploy your models in production as new data becomes available.

2. Resources with links to everything ([_picked up from this comment_]()):
- [Elements of Statistical Learning](http://statweb.stanford.edu/~tibs/ElemStatLearn/printings/ESLII_print10.pdf)
- [Andrew Ng's Coursera Course](https://www.coursera.org/learn/machine-learning/home/info)
- [The Deep Learning Book](https://www.deeplearningbook.org/front_matter.pdf)
- [Put TensorFlow or PyTorch on a Linux box and run examples](http://cs231n.github.io/aws-tutorial/)
- [Keep up with the research](https://arxiv.org) but I recommend checking out Andrey Karpathy's [Arxiv Sanity Preserver](http://www.arxiv-sanity.com/)
- [Resume Filler - Kaggle Competitions](https://www.kaggle.com)

3. [Data Science Roadmap](https://medium.com/data-science-group-iitr/road-map-to-data-science-7bc00e20a735) by Anirudh Dagar, Data Science Group, IIT Roorkee.

![image](https://user-images.githubusercontent.com/31373860/78146914-6cd00800-7450-11ea-8bd8-5d45cf9dccca.png)

If you need a more progressive roadmap, one where you master a specific topic before moving over to something else. For example, master _Linear Algebra_ before moving to _Probability & Statistics_ & so on. In all honesty, I wouldn't recommend this path. It would take you a lifetime to learn _everything_ before you can even build a simple Neural Net!

**My advice?**

**Focus 70% of your time & effort on projects. Spend the remaining amount of time on courses.**

Good luck! :)

**Comment by waciumawanjohi** [comment]
Hi. I'm Waciuma Wanjohi, I'm the lead academic maintainer of OSSU's Computer Science curriculum. I just came upon this issue and was pleased to see that there are a number of individuals interested in the state of the Data Science curriculum.

I see two great needs for the data science curriculum:

1) Replace courses that are no longer being offered. In the CS curriculum, when someone notices that a course is no longer available, they open an issue. Then students start offering suggestions for replacements. You can see an example of what happened when Stanford ended its Lagunita platform: https://github.com/ossu/computer-science/issues/645

2) Ensure that the recommendations match academic expectations. OSSU has a central promise, to enable students to learn the undergraduate curriculum of any discipline, whether that's CS or data-science. In order to do so, OSSU must evaluate our recommendations against curricular guidelines from relevant bodies. For CS, that means that we are using the [CS2013](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf) document from the ACM and IEEE. The equivalent document for data science is [Curriculum Guidelines for
Undergraduate Programs in Data Science](https://www.amstat.org/asa/files/pdfs/EDU-DataScienceGuidelines.pdf).

Data Science needs contributors that can rebuild this curriculum. In the immediate term: If you find a dead link, please open an issue. If you know a course that would be a good replacement, please suggest it. In the medium term: If you are passionate about the field of data science, read through that guidelines for undergraduate programs and start a collaborative document that shows where OSSU's curriculum teaches too much or too little.

I'm happy to help. I've made sure that I'll get notifications of new issues. When I see consensus in an issue, I'll make sure it becomes a pull request and is merged in. I look forward to the day when new students have confidence that OSSU Data Science is giving the best recommendations possible for their goals.

**Comment by skate1512** [comment]
> * [Andrew Ng's Coursera Course](https://www.coursera.org/learn/machine-learning/home/info)
I know that this course is quite famous but it hasn't been updated. Check this: https://see.stanford.edu/Course/CS229

**Comment by waciumawanjohi** [comment]
Closing this issue as there is a proposed change that will address these issues. Comment here: https://github.com/ossu/data-science/issues/61
