### ISSUE TITLE
Some wrongs I found in the courses' links

### ISSUE THREAD

**Issue by EWCunha** [ossu/data-science#59]
I made a "report" with all the courses that have any kind of problem in terms of availability, wrong URL or course change.

[Problematic Courses.xlsx](https://github.com/ossu/data-science/files/5048363/Problematic.Courses.xlsx)

There are some course at Coursera, but Coursera is free only for a 7-day period, right?

I hope that this is worth it someway.

**Comment by waciumawanjohi** [comment]
Rather than linking to a file that must be downloaded, can you link to a list that is available online? For example, as a google sheet that others can view?

As to Coursera courses, most allow students to audit. See more here: https://github.com/ossu/computer-science/blob/master/FAQ.md#are-coursera-courses-free-to-access

**Comment by EWCunha** [comment]
Yes sure!

Here is the link for the Google sheet.

https://docs.google.com/spreadsheets/d/1m3dKrfOx6MO0tKUj2fiNZ-6bgaQ8kDpl9zpT2_OXPms/edit?usp=sharing

Oh, ok. I've never paid attention to this Audit small button at Coursera... It is probably intensionally so designed

**Comment by waciumawanjohi** [comment]
Closing this issue as there is a proposed change that will address these issues. Comment here: https://github.com/ossu/data-science/issues/61
