### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by attackgnome** [ossu/data-science#67]
The repository is missing a LICENSE, propose to add MIT license consistent with the ossu/computer-science repository.

**Comment by oNjEncUREn** [comment]
I agree with this issue.  I'm not sure who makes the decision regarding which license to choose though.

**Comment by cactail** [comment]
Reminder to address this issue. MIT license is a good call but not sure if it's the best for this kind of resources.

**Comment by jeanlucaslima** [comment]
+1

**Comment by SubhamSrivatsa** [comment]
ok

**Comment by oNjEncUREn** [comment]
@waciumawanjohi Are you the one responsible for making OSSU licensing decisions?

**Comment by waciumawanjohi** [comment]
It is true that some of the other repos list the MIT license. I don't think it's the right license for this repo as the license is written for code and this repo does not host code.

I believe the Creative-Commons licenses are the most appropriate. This aligns with research from the IEEE, which offered the course [Foundations to Open Education and OERs Repositories](https://www.classcentral.com/course/independent-foundations-to-open-education-and-oers-repositories-edicion-especial-19301). While that course is no longer online (to my frustration) some of the thrust of that course can be found in [this article](https://www.mdpi.com/2071-1050/12/18/7346/htm). In the course and in the article references to licenses are always to creative-commons licenses rather than to software licenses (MIT, Apache, BSD, etc).

**Comment by attackgnome** [comment]
@waciumawanjohi, based on your comments maybe the "Creative Commons Attribution Share Alike 4.0" is the best option available from github. 

It would allow for adaptions of this work to be shared as long as others share alike, which I think is in the spirit of the OSSU project.

**Comment by waciumawanjohi** [comment]
I'm happy to add this license

https://creativecommons.org/licenses/by-sa/4.0/

**Comment by attackgnome** [comment]
@waciumawanjohi great. That is the exact license I was thinking of
